//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tpurchase
    {
        public int PId { get; set; }
        public string PName { get; set; }
        public string PQuantity { get; set; }
        public Nullable<int> PPurchaseprice { get; set; }
        public Nullable<int> PAdd { get; set; }
        public string EName { get; set; }
        public string EPhone { get; set; }
        public string EAddress { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
